import {
  Accessibility,
  Archive,
  Armchair,
  Baby,
  Beef,
  Bird,
  Bolt,
  Bone,
  Boxes,
  Briefcase,
  Brush,
  BrushCleaning,
  Building2,
  Bus,
  Cable,
  CalendarRange,
  Camera,
  Car,
  CarFront,
  Cat,
  Cctv,
  ChefHat,
  Cigarette,
  CircleUser,
  Clapperboard,
  Cog,
  Construction,
  CookingPot,
  Cpu,
  Dice5,
  Dog,
  DoorClosed,
  Drill,
  Droplet,
  Droplets,
  Dumbbell,
  Factory,
  Fish,
  FlaskConical,
  Footprints,
  Gamepad2,
  Gift,
  Guitar,
  Hammer,
  HandHeart,
  HardHat,
  Headphones,
  Heart,
  HeartHandshake,
  Home,
  House,
  HousePlus,
  KeyRound,
  Lamp,
  LandPlot,
  Laptop,
  Lightbulb,
  MapPinned,
  Mars,
  Microwave,
  Milk,
  Mountain,
  PackageCheck,
  Paintbrush,
  Palette,
  PanelTop,
  Paperclip,
  PartyPopper,
  PawPrint,
  Phone,
  Pill,
  Printer,
  Rabbit,
  RockingChair,
  Router,
  Ruler,
  Sailboat,
  Sandwich,
  Scale,
  Scissors,
  Scooter,
  Shirt,
  ShoppingBasket,
  Shovel,
  Smartphone,
  SmilePlus,
  Sofa,
  Sparkles,
  Speaker,
  SprayCan,
  Sprout,
  Stethoscope,
  Store,
  Tablet,
  Tag,
  Terminal,
  ToyBrick,
  Tractor,
  Truck,
  Tv,
  Venus,
  Volleyball,
  Warehouse,
  WashingMachine,
  Watch,
  Wheat,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Every icon this file knows the name of -- used by the admin category
 * picker (an admin can still override any category's icon in the DB) and
 * as the source for CATEGORY_ICON_BY_SLUG below. */
export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  Accessibility,
  Archive,
  Armchair,
  Baby,
  Beef,
  Bird,
  Bolt,
  Bone,
  Boxes,
  Briefcase,
  Brush,
  BrushCleaning,
  Building2,
  Bus,
  Cable,
  CalendarRange,
  Camera,
  Car,
  CarFront,
  Cat,
  Cctv,
  ChefHat,
  Cigarette,
  CircleUser,
  Clapperboard,
  Cog,
  Construction,
  CookingPot,
  Cpu,
  Dice5,
  Dog,
  DoorClosed,
  Drill,
  Droplet,
  Droplets,
  Dumbbell,
  Factory,
  Fish,
  FlaskConical,
  Footprints,
  Gamepad2,
  Gift,
  Guitar,
  Hammer,
  HandHeart,
  HardHat,
  Headphones,
  Heart,
  HeartHandshake,
  Home,
  House,
  HousePlus,
  KeyRound,
  Lamp,
  LandPlot,
  Laptop,
  Lightbulb,
  MapPinned,
  Mars,
  Microwave,
  Milk,
  Mountain,
  PackageCheck,
  Paintbrush,
  Palette,
  PanelTop,
  Paperclip,
  PartyPopper,
  PawPrint,
  Phone,
  Pill,
  Printer,
  Rabbit,
  RockingChair,
  Router,
  Ruler,
  Sailboat,
  Sandwich,
  Scale,
  Scissors,
  Scooter,
  Shirt,
  ShoppingBasket,
  Shovel,
  Smartphone,
  SmilePlus,
  Sofa,
  Sparkles,
  Speaker,
  SprayCan,
  Sprout,
  Stethoscope,
  Store,
  Tablet,
  Tag,
  Terminal,
  ToyBrick,
  Tractor,
  Truck,
  Tv,
  Venus,
  Volleyball,
  Warehouse,
  WashingMachine,
  Watch,
  Wheat,
  Wrench,
  Zap,
};

export const CATEGORY_ICON_OPTIONS: { name: string; Icon: LucideIcon }[] = Object.entries(
  CATEGORY_ICON_MAP
).map(([name, Icon]) => ({ name, Icon }));

// One specific, hand-matched icon per category and subcategory (verified
// 1:1 against every real category/subcategory slug in the database — see
// scratch-verify-slugs.js used while building this). Subcategories each
// get their own distinct icon rather than inheriting the parent's, which
// was the root cause of every child in a flyout showing the same icon as
// its parent (e.g. every Vehicles subcategory rendering the Car icon).
const TOP_LEVEL_ICON_BY_SLUG: Record<string, LucideIcon> = {
  vehicles: Car,
  property: Home,
  "phones-tablets": Smartphone,
  electronics: Laptop,
  fashion: Shirt,
  "home-furniture-appliances": Sofa,
  "beauty-personal-care": Sparkles,
  services: Wrench,
  "repair-construction": Hammer,
  "commercial-equipment-tools": Briefcase,
  "leisure-activities": Dumbbell,
  "babies-kids": Baby,
  "food-agriculture-farming": ShoppingBasket,
  "animals-pets": PawPrint,
};

const SUBCATEGORY_ICON_BY_SLUG: Record<string, LucideIcon> = {
  // Vehicles
  "buses-microbuses": Bus,
  cars: Car,
  "construction-heavy-machinery": Construction,
  "motorcycles-scooters": Scooter,
  "personal-mobility": Accessibility,
  "trucks-trailers": Truck,
  "vehicle-parts-accessories": Cog,
  "watercraft-boats": Sailboat,

  // Property
  "commercial-property-for-rent": Building2,
  "event-centres-venues-workstations": PartyPopper,
  "houses-apartments-for-rent": KeyRound,
  "houses-apartments-for-sale": House,
  "land-plots-for-rent": MapPinned,
  "land-plots-for-sale": LandPlot,
  "new-builds": HousePlus,
  "short-let": CalendarRange,

  // Phones & Tablets
  "phone-tablet-accessories": Cable,
  "mobile-phones": Phone,
  "smart-watches": Watch,
  tablets: Tablet,

  // Electronics
  "audio-music-equipment": Speaker,
  headphones: Headphones,
  "laptops-computers": Cpu,
  "networking-products": Router,
  "photo-video-cameras": Camera,
  "printers-scanners": Printer,
  "security-surveillance": Cctv,
  "tv-video-equipment": Tv,
  "video-game-consoles": Gamepad2,

  // Fashion
  "baby-kids-fashion": Baby,
  "mens-fashion": Mars,
  "womens-fashion": Venus,

  // Home, Furniture & Appliances
  furniture: Armchair,
  "garden-supplies": Shovel,
  "home-accessories": Lamp,
  "home-appliances": WashingMachine,
  "household-chemicals": SprayCan,
  "kitchen-appliances": Microwave,
  "kitchenware-cookware": CookingPot,
  lighting: Lightbulb,
  "storage-organization": Archive,

  // Beauty & Personal Care
  "body-care": Droplet,
  "face-care": CircleUser,
  fragrance: FlaskConical,
  "hair-beauty": Scissors,
  makeup: Paintbrush,
  "oral-care": SmilePlus,
  "sexual-wellness": Heart,
  "beauty-tools-accessories": Brush,
  "vitamins-supplements": Pill,

  // Services
  "building-trades-services": HardHat,
  "car-services": CarFront,
  "cleaning-services": BrushCleaning,
  "computer-it-services": Terminal,
  "legal-services": Scale,
  "logistics-services": PackageCheck,
  "manufacturing-services": Factory,
  "printing-services": Printer,
  "repair-services": Cog,

  // Repair & Construction
  "building-materials-supplies": Warehouse,
  "doors-security": DoorClosed,
  "electrical-equipment": Zap,
  "electrical-hand-tools": Drill,
  "hand-tools": Wrench,
  "hardware-fasteners": Bolt,
  "measuring-testing-tools": Ruler,
  "plumbing-water-systems": Droplets,
  "windows-glass": PanelTop,

  // Commercial Equipment & Tools
  "manufacturing-equipment": Factory,
  "manufacturing-materials-supplies": Boxes,
  "medical-equipment-supplies": Stethoscope,
  "restaurant-catering-equipment": ChefHat,
  "retail-store-equipment": Store,
  "safety-equipment-protective-gear": HardHat,
  "salon-beauty-equipment": Scissors,
  "stationery-office-equipment": Paperclip,

  // Leisure & Activities
  "arts-crafts-awards": Palette,
  "books-table-games": Dice5,
  massagers: HandHeart,
  "music-video": Clapperboard,
  "musical-instruments-gear": Guitar,
  "outdoor-gear": Mountain,
  "smoking-accessories": Cigarette,
  "sports-equipment": Volleyball,

  // Babies & Kids
  "babies-kids-accessories": Gift,
  "baby-gear-equipment": RockingChair,
  "care-feeding": Milk,
  "childrens-clothing": Shirt,
  "childrens-furniture": Armchair,
  "childrens-shoes": Footprints,
  "maternity-pregnancy": HeartHandshake,
  "toys-games": ToyBrick,
  "transport-safety": CarFront,

  // Food, Agriculture & Farming
  "farm-animal-feed-supplements": Wheat,
  "farm-animals": Beef,
  "farm-machinery-equipment": Tractor,
  "food-beverages": Sandwich,
  "seeds-fertilizers": Sprout,

  // Animals & Pets
  birds: Bird,
  "cats-kittens": Cat,
  "dogs-puppies": Dog,
  fish: Fish,
  "other-animals": Rabbit,
  "pet-services": Stethoscope,
  "pets-accessories": Bone,
};

/** Flat slug -> icon lookup covering every top-level category and
 * subcategory (verified 1:1 against the live categories table). */
export const CATEGORY_ICON_BY_SLUG: Record<string, LucideIcon> = {
  ...TOP_LEVEL_ICON_BY_SLUG,
  ...SUBCATEGORY_ICON_BY_SLUG,
};

// Precedence: an admin-assigned DB icon wins if one is set (lets the
// admin picker override any category later); otherwise the curated
// slug map above; a brand-new category nobody has mapped yet falls back to
// a neutral tag icon rather than silently becoming a car.
export function resolveCategoryIcon(cat: { slug: string; icon?: string | null }): LucideIcon {
  if (cat.icon && CATEGORY_ICON_MAP[cat.icon]) return CATEGORY_ICON_MAP[cat.icon];
  return CATEGORY_ICON_BY_SLUG[cat.slug] ?? Tag;
}
