export const ADMIN_AUDIT_ACTION_LABELS: Record<string, string> = {
  "listing.status_change": "Changed listing status",
  "listing.delete": "Deleted listing(s)",
  "listing.category_change": "Changed listing category",
  "listing.expiry_extend": "Extended listing expiry",
  "listing.clear_featured": "Cleared featured badge",
  "listing.clear_bump": "Cleared bump",
  "user.suspend": "Suspended user",
  "user.restore": "Restored user",
  "user.ban": "Banned user",
  "user.unban": "Unbanned user",
  "user.delete": "Deleted user",
  "user.warn": "Warned user",
  "user.verify_toggle": "Toggled seller verification",
  "admin.role_change": "Changed admin role",
  "admin.grant_access": "Granted admin access",
  "report.status_change": "Changed report status",
  "report.priority_toggle": "Toggled report priority",
  "report.resolved_via_warn": "Resolved report by warning seller",
  "report.resolved_via_suspend": "Resolved report by suspending seller",
  "report.resolved_via_delete": "Resolved report by deleting listing",
  "moderation.flag_status_change": "Changed moderation flag status",
  "payment.mark_active": "Manually activated purchase",
  "payment.revoke": "Revoked purchase",
  "category.create": "Created category",
  "category.update": "Updated category",
  "category.reorder": "Reordered category",
  "category.delete": "Deleted category",
  "location.district_rename": "Renamed district",
  "location.region_rename": "Renamed region",
  "location.toggle_enabled": "Toggled location enabled",
  "location.district_reorder": "Reordered district",
  "location.region_reorder": "Reordered region",
  "location.delete": "Deleted location",
  "plan.create": "Created premium plan",
  "plan.update": "Updated premium plan",
  "plan.toggle_enabled": "Toggled premium plan enabled",
  "plan.delete": "Deleted premium plan",
  "setting.flag_toggle": "Toggled feature flag",
  "setting.value_update": "Updated site setting",
  "feedback_report.status_change": "Changed feedback report status",
  "feedback.delete": "Deleted feedback",
  "feedback.warn_author": "Resolved feedback report by warning author",
  "support_ticket.status_change": "Changed support ticket status",
};
